[[constraint]]
  name = "github.com/containerd/containerd"
  version = "1.2.0"

[[constraint]]
  name = "github.com/openfaas/faas"
  version = "0.9.8"

[[constraint]]
  name = "github.com/openfaas/faas-provider"
  version = "0.7.1"

[prune]
  go-tests = true
  unused-packages = true


[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"
